name: SSH Connect_OSTAD

on:
  push:
    branches:
      - main

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Beforessh
        run: |
          ls -la
  
       # ✅ STEP 1: Copy frontend folder to EC2
      - name: SCP frontend to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "Front_end"
          target: "/home/ubuntu/"

          
      - name: Connect via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

          script: |
            uname -a
            whoami
            pwd
            
